const mongoose = require("mongoose");

const dashboardColumnListInitSchema = new mongoose.Schema({
  memberId: String,
  memberActive: String,
  membershipEmail: String,
  requestDate: String,
  validationDate: String,
  compagnyRepresentName: String,
  compagnyRepresentLastname: String,
  compagnyRepresentFunction: String,
  compagnyRepresentQuote: String,
  compagnyRepresentPhoto: String,
  compagnyName: String,
  compagnyAdress: String,
  compagnyAdditionalAdress: String,
  compagnyPostalCode: String,
  compagnyCity: String,
  compagnyTelephon: String,
  compagnyEmail: String,
  compagnyWebside: String,
  compagnyFacebook: String,
  compagnyInstagram: String,
  compagnyLinkedin: String,
  compagnyTwitter: String,
  compagnyActivityArea: String,
  compagnyActivityDescription: String,
  compagnyLogo: String,
  compagnyCoverPhoto: String,
  compagnyPresentationFile: String,
  charterSigning: String,
});

const dashboardColumnListShowSchema = new mongoose.Schema({
  memberId: String,
  memberActive: String,
  membershipEmail: String,
  requestDate: String,
  validationDate: String,
  compagnyRepresentName: String,
  compagnyRepresentLastname: String,
  compagnyRepresentFunction: String,
  compagnyRepresentQuote: String,
  compagnyRepresentPhoto: String,
  compagnyName: String,
  compagnyAdress: String,
  compagnyAdditionalAdress: String,
  compagnyPostalCode: String,
  compagnyCity: String,
  compagnyTelephon: String,
  compagnyEmail: String,
  compagnyWebside: String,
  compagnyFacebook: String,
  compagnyInstagram: String,
  compagnyLinkedin: String,
  compagnyTwitter: String,
  compagnyActivityArea: String,
  compagnyActivityDescription: String,
  compagnyLogo: String,
  compagnyCoverPhoto: String,
  compagnyPresentationFile: String,
  charterSigning: String,
});

const dashboardSchema = new mongoose.Schema({
  dashboardColumnListInit: [dashboardColumnListInitSchema],
  dashboardColumnListShow: [dashboardColumnListShowSchema],
  dashboardPagination: Array,
});

module.exports = mongoose.model("Dashboard", dashboardSchema);
