const mongoose = require("mongoose");

const userSchema = new mongoose.Schema({
  membershipEmail: String,
  memberActive: String,
  membershipHashPassword: String,
  requestDate: String,
  validationDate: String,
  compagnyRepresentFirstname: String,
  compagnyRepresentLastname: String,
  compagnyRepresentFunction: String,
  compagnyRepresentQuote: String,
  compagnyRepresentPhoto: String,
  compagnyName: String,
  compagnyAdress: String,
  compagnyAdditionalAdress: String,
  compagnyPostalCode: String,
  compagnyCity: String,
  compagnyTelephone: String,
  compagnyEmail: String,
  compagnyWebside: String,
  compagnyFacebook: String,
  compagnyInstagram: String,
  compagnyLinkedin: String,
  compagnyTwitter: String,
  compagnyActivityArea: String,
  compagnyActivityDescription: String,
  compagnyLogo: String,
  compagnyCoverPhoto: String,
  compagnyPresentationFile: String,
  charterSigning: String,
  RGPDSigning: String,
  paymentMode: String,
});

module.exports = mongoose.model("MemberShip", userSchema);
